version: "3"
services:
    db:
      restart: always
      image: mariadb
      container_name: myapp_db
      environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - MYSQL_DATABASE=dev
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 3306:3306
    app:
      build: ./
      command: sh -c "sleep 20s ; python3 ./app.py"
      depends_on:
        - db